### PR TITLE
fix(create-email): Move `"react-email"` package to devDependencies for the template

### PR DESCRIPTION
**Pull request by Briscoooe**
The [manual setup](https://react.email/docs/getting-started/manual-setup#2-install-dependencies) suggests adding `react-email` as a devDependency (with the `-d` flag), so the behaviour should be the same here. The package is not required at runtime and adding at as a regular dependency, rather than a devDependency, adds hundreds of MBs of JS to production builds.

### CODE REVIEW

**Comment by gabrielmfern** [comment]
Good catch!

Could you just add in a changeset for the `create-email` package?

**Comment by Briscoooe** [comment]
Getting errors around `react-email/components` versions when trying to generate the changeset. Is it an issue with the branch/fork or something else?

```
Package "web" must depend on the current version of "@react-email/components": "0.0.26-canary.3" vs "npm:@react-email/components@latest"
🦋  error Error: Failed to find where HEAD diverged from main. Does main exist?
🦋  error     at getDivergedCommit (/Users/brianbriscoe/Code/react-email/node_modules/.pnpm/@changesets+git@3.0.0/node_modules/@changesets/git/dist/changesets-git.cjs.js:66:11)
🦋  error     at async getChangedFilesSince (/Users/brianbriscoe/Code/react-email/node_modules/.pnpm/@changesets+git@3.0.0/node_modules/@changesets/git/dist/changesets-git.cjs.js:198:22)
🦋  error     at async Object.getChangedPackagesSinceRef (/Users/brianbriscoe/Code/react-email/node_modules/.pnpm/@changesets+git@3.0.0/node_modules/@changesets/git/dist/changesets-git.cjs.js:239:24)
🦋  error     at async getVersionableChangedPackages (/Users/brianbriscoe/Code/react-email/node_modules/.pnpm/@changesets+cli@2.27.7/node_modules/@changesets/cli/dist/changesets-cli.cjs.js:200:27)
🦋  error     at async add (/Users/brianbriscoe/Code/react-email/node_modules/.pnpm/@changesets+cli@2.27.7/node_modules/@changesets/cli/dist/changesets-cli.cjs.js:466:35)
🦋  error     at async run (/Users/brianbriscoe/Code/react-email/node_modules/.pnpm/@changesets+cli@2.27.7/node_modules/@changesets/cli/dist/changesets-cli.cjs.js:1300:5)
```

**Comment by gabrielmfern** [comment]
@Briscoooe Had this myself a while back, it's just that you didn't pull the main branch. Try checking out to it `git checkout main`.

**Comment by Briscoooe** [comment]
Should be good now @gabrielmfern

**Review by gabrielmfern — APPROVED** [review]

**Pull request merged**
