### PR TITLE
chore(web): Add `aws-verify-email` example to page of examples

### PR DESCRIPTION
**Pull request by thecodeinfluencer**
Holla!

- This PR adds aws-verify-email to the https://react.email/examples page

### CODE REVIEW

**Review by gabrielmfern — DISMISSED** [review]

**Comment by gabrielmfern** [comment]
@thecodeinfluencer Hey, sorry for taking a bit to merge this, could you fix the conflicts here? If I do, my approving review won't make it mergeable.

**Comment by thecodeinfluencer** [comment]
> @thecodeinfluencer Hey, sorry for taking a bit to merge this, could you fix the conflicts here? If I do, my approving review won't make it mergeable.

Done @gabrielmfern!

**Comment by thecodeinfluencer** [comment]
Any update on this @gabrielmfern?
Resolved the merge conflicts.

**Comment by gabrielmfern** [comment]
@thecodeinfluencer Yup, you just need to remove the trailing `.tsx` from the example you added in. I made a review comment for you some time ago:
image

**Comment by thecodeinfluencer** [comment]
> @thecodeinfluencer Yup, you just need to remove the trailing `.tsx` from the example you added in. I made a review comment for you some time ago:

Must have missed this. It's done now!

**Review by gabrielmfern — APPROVED** [review]

**Comment by gabrielmfern** [comment]
@thecodeinfluencer Seems like we missed adding a picture of the example, like the ones we have for the other examples,
so now the app, at least on canary, has the example like:

image

See https://react-email-96aeikr1x-resend.vercel.app/examples. Could you open another PR taking a look into this?

**Comment by thecodeinfluencer** [comment]
> @thecodeinfluencer Seems like we missed adding a picture of the example, like the ones we have for the other examples, so now the app, at least on canary, has the example like:
>
> See https://react-email-96aeikr1x-resend.vercel.app/examples. Could you open another PR that adds the missing picture?

Let me create a new PR to fix that

**Comment by thecodeinfluencer** [comment]
@gabrielmfern https://github.com/resend/react-email/pull/1375

**Pull request merged**
