### PR TITLE
feat(react-email, create-email): Use internal implementation for tree function instead of using `tree-cli`

### LINKED ISSUE #1153: Consider migrating off unmaintained `tree-cli`
I saw that `react-email` recently [switched](https://github.com/resend/react-email/pull/1027/files#diff-79ed911b0cab61ba07ff059e7b509532b27dbf22c33f9c6b279a9aa1315f9b5dR43) from https://github.com/yangshun/tree-node-cli to https://github.com/MrRaindrop/tree-cli to allow installation behind a corporate proxy.

`tree-cli` hasn't been updated in 4 years, and includes a lot of dangerously outdated packages (see [analysis](https://snyk.io/advisor/npm-package/tree-cli)), which is throwing some security concerns in my dependency analyzer.

It would be great if this dependency could be dropped, in favor of writing the functionality internally!

### PR DESCRIPTION
**Pull request by gabrielmfern**
## What was the issue?

Some time ago we switched from using `tree-node-cli` to using `tree-cli` as `tree-node-cli` was causing
issues for someone trying to download the CLI behind a corporate proxy. 
The new library `tree-cli` though is unmaintained and seems to depend on some libraries
that were being caught by some security measures mentioned here #1153.

This fixes this by having our implementation of the tree functionality
both in `create-email` and in `react-email` which is not very hard to maintain
and comes along with tests to verify this works properly.

## How can I test to make sure it's fixed?

1. Run `node src/index.js` inside of `./packages/create-email`
2. Verify that the generated tree is appropriate

If you try running the `export` command from the CLI, which is the other place that depends on
this `tree` functionality, you will probably have an error here which #1214 fixes.

Closes  #1153

### CODE REVIEW

**Comment by michaelhays** [comment]
Hey @gabrielmfern, are we just waiting for a review to get this merged? Anything I can do to help?

**Review by vcapretz — APPROVED** [review]

**Review by vcapretz — APPROVED** [review]

**Comment by gabrielmfern** [comment]
@michaelhays Hey, heads up, we just released this under `react-email@2.1.1-canary.0` and `create-email@0.0.24-canary.0`. Let me know if things work out fine for you on these!

**Comment by michaelhays** [comment]
Thank you sir! I'll try them out!

**Comment by michaelhays** [comment]
Following up, 2.1.1 no longer gives me the Snyk warnings :pray: Thanks again!

**Pull request merged**
