### PR TITLE
fixed tooltip content invisible on light themes

### PR DESCRIPTION
**Pull request by kaustabhws**
### Changes Made
- Added a new custom hook `useThemeDetector` to detect the user's preferred color scheme.
- Integrated `useThemeDetector` hook in `tooltip.tsx` to conditionally change the background color of tooltips based on the detected theme.

### Fixes
This pull request addresses issue #1326.

### CODE REVIEW

**Comment by kaustabhws** [comment]
Please review the PR. I'm not sure why test is failed. Let me know and I'll update

**Comment by gabrielmfern** [comment]
Might be a bit confusing, but we run linting in the `test` CI, that's why it's failing here. So, to find out why, you can run `pnpm lint` inside `packages/react-email` or even in the root of the project, and it will give you some insight.

One more thing is, after thinking a bit about it, the application doesn't yet support different themes, so it actually might be better off to, until we support multiple themes, to use a `text-white` on the tooltip.

**Comment by gabrielmfern** [comment]
Oh, and once you update your branch with our `canary`, it's better off to do so with a rebase instead of a merge, makes it much easier to view the diff here on GitHub.

**Comment by gabrielmfern** [comment]
Closing this as stale

**Pull request closed without merging**
