### PR TITLE
feat(render): Substitute implementation of `render` with the one from `renderAsync`

### PR DESCRIPTION
**Pull request by gabrielmfern**
This deprecates `renderAsync` and replaces the implementation of `render` with the implementation
from `renderAsync`. Along with this implementation change of `render`, I also added the unit tests from `renderAsync` to `render`.

Since many of our tests use the `render` utility, I had to change them all to make sure that the `render`'s returned Promise is now treated correctly.

I believe this is the best course of action for a couple of reasons that I go in depth on #1144.

### Issues that this can help fix

- #1080 
- #1029 
- #977

### CODE REVIEW

**Comment by antoinerousseau** [comment]
does this mean the `react-email` preview page would support async components? (RSC)
that would be great!

**Comment by gabrielmfern** [comment]
@antoinerousseau That'd be pretty cool and I'll still experiment with that but no, not yet, mostly it would be possible to have something like react-query.

**Comment by edeuxk** [comment]
Hello @gabrielmfern thank you for this amazing work.
Does your PR includes the ReadableByteStreamController with Safari ?

**Comment by gabrielmfern** [comment]
>  Does your PR includes the ReadableByteStreamController with Safari ?
I don't think so. Could you link some resources? I've never heard of that

**Comment by RomainGueffier** [comment]
> > Does your PR includes the ReadableByteStreamController with Safari ?
> 
> @edeuxk I don't think so. Could you link some resources? I've never heard of that

Hi @gabrielmfern we mentioned it in this issue https://github.com/resend/react-email/issues/1080#issuecomment-1855402967

**Comment by theosenoussaoui** [comment]
Hello, I was waiting for this PR to be resolved since it would have allowed (if I understood correctly), the upgrade to the latest Tailwind version.

Is there a particular reason for this closing ? Will any Tailwind version past 3.3.2 be supported in the near future ? 

Regards.

**Pull request closed without merging**
