### PR TITLE
chore(react-email): Bump `render` version

### PR DESCRIPTION
**Pull request by GentikSolm**
- fix: upgrade render version to 0.0.9
- fix: remove deprecated app dir experiemental flag from next config

Upgrades resend render version from 0.0.7 to 0.0.9 to fix renderToReadableStream issue.

Also removes appDir experimental flag as it is now deprecated

### CODE REVIEW

**Review by bukinoshita — APPROVED** [review]

**Comment by prokopsimek** [comment]
Is it possible to merge this PR, or is there even a way to test this PR?

**Comment by wowjulian** [comment]
Thank you for the fix! Can someone merge this? 

https://github.com/resend/react-email/issues/1029

The issue above has been present for a month, I believe this fixes it. Thanks!

**Comment by GentikSolm** [comment]
I've moved to https://github.com/shellscape/jsx-email and it works flawlessly.

**Comment by gabrielmfern** [comment]
Closing this in favor of #1073. This has been released on `react-email@canary` everyone and should be working without problems.

**Pull request closed without merging**
