### PR TITLE
fix(render): Default import for `js-beautify`

### PR DESCRIPTION
**Pull request by broisnischal**
- Fix: `fix(react-email)` : import of js-beautify to use the entire module due to compatibility issues with ESM

### CODE REVIEW

**Comment by gabrielmfern** [comment]
Is the default import also failing for Remix here? In theory it should work

**Comment by broisnischal** [comment]
yep, it was failing fsr, i tried my updated via installing locally and it is working fine!

**Comment by gabrielmfern** [comment]
> yep, it was failing fsr, i tried my updated via installing locally and it is working fine!

Are you sure this wasn't caused by the `resend` SDK? A few users were still having the issue because of it and the `react` option due to it using the `0.0.11` version of render.

**Comment by broisnischal** [comment]
@gabrielmfern I tried locally, and it is working very fine after I change the import, I am pretty much sure this will solve the other's issues as well.

**Comment by gabrielmfern** [comment]
I tried reproducing here, and got the following results:
| Package | Version | Type of import from `js-beautify` | Works? |
|--------|--------|--------|--------|
| `@react-email/render` | `0.0.12` | Default import | ✅ |
| `resend` | `3.1.0` | Default import | ✅ |
|--------|--------|--------|--------|
| `@react-email/render` | `0.0.11` | Named import | ❌ |
| `resend` | `3.0.0` | Named import | ❌ | 

The default import seems to be working fine. I think you might be using `resend@3.0.0` and confusing the errors it throws because it uses `@react-email/render` under the hood and on `3.0.0` it depended on `0.0.11`.
These were not necessarily ran using Remix but I ran them using node pure ESM which I believe is what Remix runs on the server here.

Going to close this for now, if you provide more arguments to why this might work better than the default import and verify the cases I mentioned as working above do not work for you I'll reopen it and we might reconsider here.

On another note, I think doing a [namespace import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#forms_of_import_declarations) here might be very unsafe as it might come as an object containing a default property that then contains the actual module in my experience.

**Pull request closed without merging**
