### PR TITLE
fix(client): added success feedback on successful email sent

### PR DESCRIPTION
**Pull request by lordelogos**
## Pull Request Description:
This is my proposed fixed for issue [#714]. It contains the following: 
- A success notification that will pop up for a specified duration on successful email send
- Removed an unused checkbox in the `send` component

You can see a demo below:
react-email-success-toast-demo

### CODE REVIEW

**Comment by bukinoshita** [comment]
Can we use https://www.radix-ui.com/docs/primitives/components/toast instead? We should also use the radix colors.

**Comment by lordelogos** [comment]
Ping @bukinoshita

**Comment by zenorocha** [comment]
We just added a new toast for this. Thanks @lordelogos for thinking ahead of time on this :)

**Comment by lordelogos** [comment]
Thanks for the feedback @zenorocha. Happy to see the progress of the preview client

**Pull request closed without merging**
